### ISSUE TITLE
Schema Validation Throws An Error

### ISSUE THREAD

**Issue by vladimir-trifonov** [appcelerator/appc-connector-utils#1]
Actual behavior: If the *transformer function*(https://github.com/appcelerator/appc-connector-utils/blob/master/lib/schema/api.js#L11) returns empty schema the validator throws an error(`Cannot read property 'objects' of undefined`).

Expected behavior: Should continue with an empty schema.

**Comment by pltod2** [comment]
Add support and test case for this one
