### ISSUE TITLE
Error if options param is undefined

### ISSUE THREAD

**Issue by vladimir-trifonov** [appcelerator/appc-connector-utils#15]
https://github.com/appcelerator/appc-connector-utils/blob/master/lib/utils/arrow.js#L35

**Comment by pltod2** [comment]
Functionality for dealing with container and connector is currently reimplemented. So the error is kind of fixed in 0.0.9 https://github.com/appcelerator/appc-connector-utils/commit/7e22d3373a683e4d2aa61dbdf7c934823414463d
