### ISSUE TITLE
Adding namespace - undefined

### ISSUE THREAD

**Issue by vladimir-trifonov** [appcelerator/appc-connector-utils#2]
`https://github.com/appcelerator/appc-connector-utils/blob/master/lib/model/api.js#L54`

Should not add namespace `undefined` if *options.namespace* is not specified.

**Comment by pltod2** [comment]
Fixed with https://github.com/appcelerator/appc-connector-utils/commit/8aa7600eb83d5ffb580699b7db52e9e4ff2d0873
