### ISSUE TITLE
Metadata is not an array

### ISSUE THREAD

**Issue by vladimir-trifonov** [appcelerator/appc-connector-utils#4]
Expected: Metadata should be validated as object:
https://github.com/appcelerator/appc-connector-utils/blob/master/lib/schema/contract.js#L43

i.e. : `metadata: Joi.array()` should be replaced with `metadata: Joi.object()`

**Comment by pltod2** [comment]
Fixed with https://github.com/appcelerator/appc-connector-utils/commit/cc9f40a75799d81a2aa0c0c23bf809c19522c45f
