### ISSUE TITLE
Missing `model` prop in schemas validations

### ISSUE THREAD

**Issue by vladimir-trifonov** [appcelerator/appc-connector-utils#7]
Please add `model: Joi.string()` in the both contracts:

https://github.com/appcelerator/appc-connector-utils/blob/master/lib/schema/contract.js#L29
https://github.com/appcelerator/appc-connector-utils/blob/master/lib/model/contract.js#L3

**Comment by pltod2** [comment]
Fixed with https://github.com/appcelerator/appc-connector-utils/commit/41567a9d90a571965d81ddad161566d8d107a91f
